[package]
name = "xgen"
version = "1.0.0"
authors = ["Welles"]

[addresses]
xgen_addr = "c3257382628bd3ac1c10acb4d7c7b5896aa84350e24bcab89e8443445faa0f5b"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]