[package]
name = "xgen"
version = "1.0.0"
authors = ["Welles"]

[addresses]
xgen_addr = "0xe6c595950a38dedc2a967ef78a7ab7ef802c8344deb7c1f2236015a7e213796c"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]